### ISSUE TITLE
_insertBefore issue

### ISSUE THREAD

**Issue by bazineta** [xlfishbone/marionette.morphdom#2]
In the Collection _insertBefore override, the $dom.before function gets called with an undefined second parameter, and  appears to have the effect of appending not to the collection element, but to the 'currentView' element.  Basically, it's not morphing the collection; rather it's morphing the currentView.

**Comment by xlfishbone** [comment]
Ok. Nice find.

I was actually thinking about removing some of the collection overrides bc
after looking at them they seem to only be dealing with doc fragments
anyway so there really is no need in morphing them and is probably
detrimental to performance. I hadn't had any issues so I didn't put in the
time.

I will look at this more closely in the morning. Pull request are always
welcome if you feel you got a fix.

**Comment by xlfishbone** [comment]
fixed with commit bc49f182500981248ef4f34522232d1ae9941947
